version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 36025147
      POSTGRES_DB: fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data
    ports:
      - "5433:5432"
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:36025147@db/fastapi"
    ports:
      - "8000:8000"
    volumes:
      - .:/home/app
volumes:
  postgres_data: